server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active:
      - local
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
        - id: keycloak
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - RewritePath=/auth/(?<segment>.*), /realms/SWP/$\{segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SWP
          jwk-set-uri: http://localhost:8080/realms/SWP/protocol/openid-connect/certs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    root: INFO
