# The k8s profile contains settings for k8s environments.
# All environments - staging, acceptance and production - use this profile.
# Variants for environments are supported by using environment variables in the k8s deployments.
management:
  server:
    port: 8000
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
    web:
      exposure:
        include: "*"
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://iam.swp.a7t-t-01.auruscent.com/auth/realms/swp
          jwk-set-uri: https://iam.swp.a7t-t-01.auruscent.com/auth/realms/swp/protocol/openid-connect/certs
