name: Gradle Test
on:
  push:
    branches:
      - "feature/*"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    uses: Auruscent/common-workflows/.github/workflows/gradle-test.yml@main
    secrets: inherit
    with:
      java_version: "21"
      profile: "staging"
